/**
 * @file Shared types, `SCHEMA_VERSION`, and EventMap definitions for Shell–MFE
 * communication (`ModuleStatus`, `ModuleSize`, `ModuleIdentity`, `InstanceId`,
 * `MfeEventMap`, `ShellEventMap`) enabling type-safe dispatch and listen.
 *
 * @see {@link file://./events.ts} for event name constants.
 * @see {@link file://./payloads.ts} for payload interfaces.
 */

import { MFE_EVENTS, SHELL_EVENTS } from './events.js';
import type {
  RequestAddModulePayload,
  RequestFullscreenPayload,
  RequestRemovePayload,
  UpdateHeaderPayload,
  ShowNotificationPayload,
  ModuleReadyPayload,
  ModuleErrorPayload,
  ModuleStatePayload,
  ThemeChangedPayload,
  VisibilityChangedPayload,
} from './payloads.js';

/** Current payload schema version for this library release. Required on every payload. */
export const SCHEMA_VERSION = 1 as const;

/**
 * Status values for a module header. Aligned with the `status` union of
 * `ModuleHeader` in `@cobranza-apps/ui` (`loading | loaded | success |
 * warning | error | dirty | null`); keep values in sync across packages.
 */
export type ModuleStatus =
  | 'loading'
  | 'loaded'
  | 'success'
  | 'warning'
  | 'error'
  | 'dirty'
  | null;

/** Width fraction of a workbench row. */
export type ModuleSize = '50%' | '100%';

/**
 * Identity of a module instance in the workspace.
 * `instanceId` is a UUID string generated by the Shell when the module is added.
 */
export interface ModuleIdentity {
  /** Remote / MFE kind, e.g. 'clients', 'debts', 'dashboard'. */
  moduleType: string;
  /** Unique per instance (UUID string); generated by the Shell. */
  instanceId: string;
}

/** Instance UUID string generated by the Shell. */
export type InstanceId = string;

/**
 * MFE → Shell event map: each `mfe:*` name literal to its payload interface.
 * Consumed by {@link createMfeEvent}, {@link dispatchMfeEvent},
 * {@link isMfeEvent}, and {@link assertMfePayload}.
 */
export interface MfeEventMap {
  [MFE_EVENTS.REQUEST_ADD_MODULE]: RequestAddModulePayload;
  [MFE_EVENTS.REQUEST_FULLSCREEN]: RequestFullscreenPayload;
  [MFE_EVENTS.REQUEST_REMOVE]: RequestRemovePayload;
  [MFE_EVENTS.UPDATE_HEADER]: UpdateHeaderPayload;
  [MFE_EVENTS.SHOW_NOTIFICATION]: ShowNotificationPayload;
  [MFE_EVENTS.MODULE_READY]: ModuleReadyPayload;
  [MFE_EVENTS.MODULE_ERROR]: ModuleErrorPayload;
}

/**
 * Shell → MFE event map: each `shell:*` name literal to its payload interface.
 * Consumed by {@link createShellEvent}, {@link dispatchShellEvent},
 * {@link isShellEvent}, and {@link assertShellPayload}.
 */
export interface ShellEventMap {
  [SHELL_EVENTS.MODULE_STATE]: ModuleStatePayload;
  [SHELL_EVENTS.THEME_CHANGED]: ThemeChangedPayload;
  [SHELL_EVENTS.VISIBILITY_CHANGED]: VisibilityChangedPayload;
}
